spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/online_exam?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQLDialect
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    username: zyw980527@foxmail.com
    password: relzkqxojqkrbhjh
    properties:
      mail:
        smtp:
          auth: true
          startrls:
            enable: true
            required: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html



